<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="10" passed="10">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="99" started-at="2019-06-01T08:49:39Z" finished-at="2019-06-01T08:49:39Z">
    <groups>
      <group name="sanity">
        <method signature="Exceptions.sanityTest()[pri:0, instance:practiceMaven.Exceptions@3ab39c39]" name="sanityTest" class="practiceMaven.Exceptions"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Default test" duration-ms="99" started-at="2019-06-01T08:49:39Z" finished-at="2019-06-01T08:49:39Z">
      <class name="practiceMaven.PriorityTest">
        <test-method status="PASS" signature="openBrowser()[pri:-1, instance:practiceMaven.PriorityTest@6fffcba5]" name="openBrowser" duration-ms="19" started-at="2019-06-01T14:19:39Z" finished-at="2019-06-01T14:19:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="advanceSearch()[pri:0, instance:practiceMaven.PriorityTest@6fffcba5]" name="advanceSearch" duration-ms="2" started-at="2019-06-01T14:19:39Z" finished-at="2019-06-01T14:19:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- advanceSearch -->
        <test-method status="PASS" signature="setup()[pri:1, instance:practiceMaven.PriorityTest@6fffcba5]" name="setup" duration-ms="2" started-at="2019-06-01T14:19:39Z" finished-at="2019-06-01T14:19:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="asearch1()[pri:2, instance:practiceMaven.PriorityTest@6fffcba5]" name="asearch1" duration-ms="3" started-at="2019-06-01T14:19:39Z" finished-at="2019-06-01T14:19:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asearch1 -->
        <test-method status="PASS" signature="search()[pri:2, instance:practiceMaven.PriorityTest@6fffcba5]" name="search" duration-ms="1" started-at="2019-06-01T14:19:39Z" finished-at="2019-06-01T14:19:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
      </class> <!-- practiceMaven.PriorityTest -->
      <class name="practiceMaven.Exceptions">
        <test-method status="PASS" signature="arithmeticError()[pri:0, instance:practiceMaven.Exceptions@3ab39c39]" name="arithmeticError" duration-ms="2" started-at="2019-06-01T14:19:39Z" finished-at="2019-06-01T14:19:39Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at practiceMaven.Exceptions.arithmeticError(Exceptions.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arithmeticError -->
        <test-method status="PASS" signature="arithmeticNoError()[pri:0, instance:practiceMaven.Exceptions@3ab39c39]" name="arithmeticNoError" duration-ms="1" started-at="2019-06-01T14:19:39Z" finished-at="2019-06-01T14:19:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arithmeticNoError -->
        <test-method status="PASS" signature="sanityTest()[pri:0, instance:practiceMaven.Exceptions@3ab39c39]" name="sanityTest" duration-ms="5" started-at="2019-06-01T14:19:39Z" finished-at="2019-06-01T14:19:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sanityTest -->
        <test-method status="PASS" signature="skipMethod()[pri:0, instance:practiceMaven.Exceptions@3ab39c39]" name="skipMethod" duration-ms="1" started-at="2019-06-01T14:19:39Z" finished-at="2019-06-01T14:19:39Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[SkipException to Skip the method]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: SkipException to Skip the method
	at practiceMaven.Exceptions.skipMethod(Exceptions.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skipMethod -->
      </class> <!-- practiceMaven.Exceptions -->
      <class name="practiceMaven.EnableDisableTest">
        <test-method status="PASS" signature="EnabledMethod()[pri:0, instance:practiceMaven.EnableDisableTest@2b80d80f]" name="EnabledMethod" duration-ms="3" started-at="2019-06-01T14:19:39Z" finished-at="2019-06-01T14:19:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EnabledMethod -->
      </class> <!-- practiceMaven.EnableDisableTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
